### ISSUE TITLE
Two bugs when saving signalrun if there is no event detected  

### ISSUE THREAD

**Issue by dyuliu** [signals-dev/Orion#92]
**Error message:**
```bash
INFO:orion.runner:Processing pipeline arima predictions on signal 11125
ERROR:orion.db.schema:Error storing signalrun 5ef409e3c2be97adf0ee798c events
Traceback (most recent call last):
  File "/home/dongyu/apps/orion/orion/db/schema.py", line 242, in end
    for start_time, stop_time, severity in events:
TypeError: 'NoneType' object is not iterable
ERROR:orion.runner:Datarun 5ef409e3c2be97adf0ee798b crashed
Traceback (most recent call last):
  File "/home/dongyu/apps/orion/orion/db/schema.py", line 242, in end
    for start_time, stop_time, severity in events:
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dongyu/apps/orion/orion/runner.py", line 99, in start_datarun
    start_signalrun(orex, datarun, signal)
  File "/home/dongyu/apps/orion/orion/runner.py", line 73, in start_signalrun
    signalrun.end(status, events)
  File "/home/dongyu/apps/orion/orion/db/schema.py", line 253, in end
    status = self.STATUS_ERROR
AttributeError: 'Signalrun' object has no attribute 'STATUS_ERROR'
INFO:orion.runner:Datarun 5ef40a5bc2be97adf0ee798d started
INFO:orion.runner:Signalrun 5ef40a5bc2be97adf0ee798e started
INFO:orion.runner:Running pipeline lstm on signal 11125
```

**BUG1:** 
TypeError: 'NoneType' object is not iterable
When there is no event detected, the variable `events` is expected as an empty list rather than None. 

**BUG2:**
Signalrun' object has no attribute 'STATUS_ERROR'
Go to base.py, line 205 - 208:
```py
STATUS_PENDING = 'PENDING'
STATUS_RUNNING = 'RUNNING'
STATUS_SUCCESS = 'SUCCESS'
STATUS_ERRORED = 'ERRORED'
```
However, in schema.py, line 253:
```py
status = self.STATUS_ERROR
```
Constant name is incorrectly used.

**Comment by sarahmish** [comment]
Fixed in #93.
